### ISSUE TITLE
Add support for 2022.1

### ISSUE THREAD

**Issue by lucasreiners** [DeveloperUtils/kotlin-function-arguments-helper#53]
After upgrading IntelliJ to version 2022.1, the plugin stopped working

<img width="338" alt="image" src="https://user-images.githubusercontent.com/1782634/163165700-2050006b-ff4c-412c-9313-a7bdb39765be.png">

**Comment by bentemple** [comment]
I added support for 2022.1 with this PR: https://github.com/DeveloperUtils/kotlin-function-arguments-helper/pull/54

I was able to build locally without issues and install in Intelli-J. Unsure if this PR will actually get merged, but I am at least unblocked on this for now, and this will hopefully unblock any of you as well.

**Comment by bentemple** [comment]
Alternatively: https://plugins.jetbrains.com/plugin/10942-kotlin-fill-class

**Comment by WorkingDevel** [comment]
Thank you @lucasreiners for noticing me and @bentemple for fixing it. I just didn't got the mail and this plugin was a little out of focus as I was sick. Now I'm back.

Irionically I started this plugin as fork of the mentioned plugin as it was not updated 😭 .

**Comment by bentemple** [comment]
IMO this plugin is still better than the above plugin :) I prefer it to fill class anyway. Glad you're no longer sick!
